data:
  random_state: 42
  raw_local_path: data/tourism.csv
  target_column: ProdTaken
  test_local_path: data/test.csv
  test_size: 0.2
  train_local_path: data/train.csv
features:
  categorical:
  - TypeofContact
  - Occupation
  - Gender
  - ProductPitched
  - MaritalStatus
  - Designation
  drop_columns:
  - CustomerID
  numerical:
  - Unnamed: 0
  - Age
  - CityTier
  - DurationOfPitch
  - NumberOfPersonVisiting
  - NumberOfFollowups
  - PreferredPropertyStar
  - NumberOfTrips
  - Passport
  - PitchSatisfactionScore
  - OwnCar
  - NumberOfChildrenVisiting
  - MonthlyIncome
huggingface:
  dataset_repo: tourism-package-dataset
  model_repo: tourism-package-xgb-model
  space_repo: tourism-package-predictor
  username: vivekvdeevi
